### ISSUE TITLE
so what's the plan about this?

### ISSUE THREAD

**Issue by idevz** [opentracing/opentracing-lua#1]
any roadmap or plan about this project?

**Comment by tedsuo** [comment]
Hi @idevz, there's been ongoing discussion and requirements gathering happening in https://gitter.im/opentracing/cross-language. We'll be proposing a plan here soon, and will make it the readme of the project so there's less confusion.

**Comment by idevz** [comment]
@tedsuo got it, thanks a lot.

**Comment by rnburn** [comment]
Closing. I proposed an API with #2 if you want to comment.
